name: helper_finder
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  flutter_svg: ^2.0.5
  map: ^1.0.1
  cached_network_image: ^3.2.0
  google_maps_flutter: ^2.1.5
  flutter_polyline_points: ^1.0.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  shared_preferences: ^2.0.15
  flutter_easyloading: ^3.0.3
  cloud_firestore: ^4.2.0
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  flutter_phone_direct_caller: ^2.1.1
  animations: ^2.0.2
  about: ^2.1.1
  contactus: ^1.2.0
  package_info_plus: ^4.0.0
  geocoding: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/file/